# Generated by Django 5.2.6 on 2025-10-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0002_viaje_lat_destino_viaje_lat_origen_viaje_lng_destino_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viaje',
            old_name='lat_destino',
            new_name='destino_lat',
        ),
        migrations.RenameField(
            model_name='viaje',
            old_name='lat_origen',
            new_name='destino_lng',
        ),
        migrations.RenameField(
            model_name='viaje',
            old_name='lng_destino',
            new_name='origen_lat',
        ),
        migrations.RenameField(
            model_name='viaje',
            old_name='lng_origen',
            new_name='origen_lng',
        ),
        migrations.AddField(
            model_name='viaje',
            name='destino',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='viaje',
            name='origen',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
