# Generated by Django 5.2.6 on 2025-10-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0003_rename_lat_destino_viaje_destino_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.ImageField(upload_to='archivos/'),
        ),
    ]
