# Generated by Django 5.2.6 on 2025-10-05 18:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0004_alter_archivo_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='archivos/'),
        ),
    ]
